"""Criação das tabelas de usuários

Revision ID: 9b10a467ed18
Revises: 
Create Date: 2025-11-07 11:57:56.423147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b10a467ed18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes')
    op.drop_table('doacoes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacoes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['usuarios.id'], name='doacoes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('solicitacoes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ong_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doacao_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.ForeignKeyConstraint(['doacao_id'], ['doacoes.id'], name=op.f('solicitacoes_ibfk_2')),
    sa.ForeignKeyConstraint(['ong_id'], ['usuarios.id'], name=op.f('solicitacoes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
